# different stages for the CICD pipeline
stages:
  # 1st stage
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/Credit_Card.csv
    outs:
    - data/raw/Credit_Card.csv